name: 🚀 Deploy Changes to cPanel
on:
  push:
    branches:
      - Main
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3 
      with:
        fetch-depth: 2

    - name: Deploy Laravel to margin
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: public
        server-dir: /htdocs
        exclude: | 
          .git/**   
          .github/**
          .env
          .htaccess
          .htaccess.sample
          .htaccess.example
          .htaccess.dist
